### ISSUE TITLE
How easy would it be to turn this into an angular universal app

### ISSUE THREAD

**Issue by jackbravo** [kmturley/appengine-nest-angular#1]
Something like https://github.com/nestjs/ng-universal

**Comment by kmturley** [comment]
You can copy the frontend folder from this version which uses Angular Universal 7.1.x:
https://github.com/kmturley/appengine-datastore-nest-angular

Or take that entire example and change the database from DataStore to your preferred DB :)

**Comment by jackbravo** [comment]
Ah nice! Thanks.

By the way, seems like Datastore is being deprecated in favor of Firestore in Datastore mode:

https://cloud.google.com/datastore/docs/firestore-or-datastore#automatic_upgrade_to_datastore_mode

**Comment by kmturley** [comment]
ah didn't know that was happening, very useful thanks!
